title: "Viral Solani"
description: "Personal Tech Blog | Kubernetes, GitLab, API Gateway & Cloud Learnings"
theme: minima

# Define header navigation pages
header_pages:
  - index.md
  - blogs.md

# Optional: Social Links (for future if you want)
# social_links:
#   - { platform: github, user_url: "https://github.com/viralsolani" }
