title: "Viral Solani"
description: "Engineering Leadership | Kubernetes | API Platforms | GitLab | Cloud Enthusiast"
theme: minima

header_pages:
  - index.md
  - blogs.md
  - cv.md

author: "Viral Solani"