title: "Viral Solani"
tagline: "Engineering Leader | Kubernetes | GitLab | Cloud Native | API Platform Specialist"
description: "Personal Blog and Portfolio"
url: "https://viralsolani.github.io"
baseurl: ""

lang: "en"
timezone: "Asia/Kolkata"

author:
  name: "Viral Solani"
  email: "viral.solani@gmail.com"
  github: viralsolani
  linkedin: viralsolani

social:
  links:
    - https://github.com/viralsolani
    - https://linkedin.com/in/viralsolani

theme: jekyll-theme-chirpy

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5
paginate_path: /page:num/

remote_theme: cotes2020/jekyll-theme-chirpy