title: "Viral Solani"
description: "CSM® | CSPO® | SAFe® | 2x AWS Certified | Agile Evangelist & Transformation Leader"
theme: minima

header_pages:
  - index.md
  - cv.md

author: "Viral Solani"

# Custom Navigation (for optional future use or theme customization)
navigation:
  - title: Home
    url: /
  - title: CV
    url: /cv/
  - title: GitLab
    url: /categories/gitlab/
  - title: Kubernetes
    url: /categories/kubernetes/
  - title: DevOps
    url: /categories/devops/