title: "Viral Solani"
description: "Engineering Leadership | Kubernetes | API Platforms | GitLab | Cloud Enthusiast"
theme: minima

header_pages:
  - index.md
  - blogs.md
  - cv.md

author:
  name: "Viral Solani"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/viralsolani"